
services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"

    command:
      - "--log.level=INFO"  # logging levels are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC.
      - "--api.dashboard=true"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

      # Bloque letsencrypt
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ajimper3009@iesromerovargas.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      ## La línea comentada --certificatesresolvers.myresolver.acme.caserver apunta al entorno de pruebas de ## Let's Encrypt. Esto es útil para evitar límites de emisión durante las pruebas.
      # # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`alejandrojimenez.tech`)"
        - "traefik.http.routers.traefik.service=api@internal"

        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=myresolver"
        # Añade autenticación test/test
        - "traefik.http.routers.traefik.middlewares=myauth"
        - "traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"

    ports:
      - "443:443"
      - "8080:8080"
      # - "8000:8000"
      # - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      # Usar cada uno SU DOMINIO .tech
      - "traefik.http.routers.whoami.rule=Host(`whoami.alejandrojimenez.tech`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  web:
    image: ${IMAGE}
    container_name: django_web
    #ports:
    #  - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn AlquilaPistas.wsgi:application --bind 0.0.0.0:8001 --workers 4 --threads 2
    restart: unless-stopped  # Asegura que el contenedor se reinicie si falla
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`AlquilaPistas.alejandrojimenez.tech`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=8000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
