# Generated by Django 5.1.7 on 2025-03-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_type', models.CharField(choices=[('inside', 'Interior'), ('outside', 'Exterior')], max_length=50)),
                ('gender_type', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('mixed', 'Mixto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
