# Generated by Django 5.1.7 on 2025-05-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquila_pistas', '0002_remove_court_gender_type_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquila_pistas.reservation'),
        ),
    ]
