# Generated by Django 5.1.7 on 2025-05-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquila_pistas', '0003_group_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='equip_type',
        ),
    ]
